package club.banyuan.sr.mapper;

import club.banyuan.sr.model.SeatRecord;
import club.banyuan.sr.model.SeatRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeatRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_record
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    long countByExample(SeatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_record
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    int deleteByExample(SeatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_record
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_record
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    int insert(SeatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_record
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    int insertSelective(SeatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_record
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    List<SeatRecord> selectByExample(SeatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_record
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    SeatRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_record
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") SeatRecord record, @Param("example") SeatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_record
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    int updateByExample(@Param("record") SeatRecord record, @Param("example") SeatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_record
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    int updateByPrimaryKeySelective(SeatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_record
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    int updateByPrimaryKey(SeatRecord record);
}