package club.banyuan.sr.model;

import java.io.Serializable;
import java.util.Date;

public class Seat implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.id
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.name
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.status
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.created_at
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.updated_at
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seat
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.id
     *
     * @return the value of seat.id
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.id
     *
     * @param id the value for seat.id
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.name
     *
     * @return the value of seat.name
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.name
     *
     * @param name the value for seat.name
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.status
     *
     * @return the value of seat.status
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.status
     *
     * @param status the value for seat.status
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.created_at
     *
     * @return the value of seat.created_at
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.created_at
     *
     * @param createdAt the value for seat.created_at
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.updated_at
     *
     * @return the value of seat.updated_at
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.updated_at
     *
     * @param updatedAt the value for seat.updated_at
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", status=").append(status);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}