package club.banyuan.sr.model;

import java.io.Serializable;
import java.util.Date;

public class SeatRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_record.id
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_record.user_id
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_record.seat_name
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private String seatName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_record.data
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_record.hour
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private Integer hour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_record.hasBooked
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private Boolean hasbooked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_record.created_at
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_record.updated_at
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seat_record
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_record.id
     *
     * @return the value of seat_record.id
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_record.id
     *
     * @param id the value for seat_record.id
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_record.user_id
     *
     * @return the value of seat_record.user_id
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_record.user_id
     *
     * @param userId the value for seat_record.user_id
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_record.seat_name
     *
     * @return the value of seat_record.seat_name
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public String getSeatName() {
        return seatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_record.seat_name
     *
     * @param seatName the value for seat_record.seat_name
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public void setSeatName(String seatName) {
        this.seatName = seatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_record.data
     *
     * @return the value of seat_record.data
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_record.data
     *
     * @param data the value for seat_record.data
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public void setData(String data) {
        this.data = data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_record.hour
     *
     * @return the value of seat_record.hour
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_record.hour
     *
     * @param hour the value for seat_record.hour
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_record.hasBooked
     *
     * @return the value of seat_record.hasBooked
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public Boolean getHasbooked() {
        return hasbooked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_record.hasBooked
     *
     * @param hasbooked the value for seat_record.hasBooked
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public void setHasbooked(Boolean hasbooked) {
        this.hasbooked = hasbooked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_record.created_at
     *
     * @return the value of seat_record.created_at
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_record.created_at
     *
     * @param createdAt the value for seat_record.created_at
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_record.updated_at
     *
     * @return the value of seat_record.updated_at
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_record.updated_at
     *
     * @param updatedAt the value for seat_record.updated_at
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_record
     *
     * @mbg.generated Fri Jun 26 11:29:51 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", seatName=").append(seatName);
        sb.append(", data=").append(data);
        sb.append(", hour=").append(hour);
        sb.append(", hasbooked=").append(hasbooked);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}